cfg_dir : config
cfg_file : config.yaml

refresh_rate : 600

csv_dir : files
fx_file : forex.files
crypto_file : crypto.files
exchanges_file : exchanges.files

default_currency : USD
timezone : GMT+2

fav_crypto_exchange : binance
cryptocompare_url : https://cryptocompare.com


heroku_name : dao6hk19nib9sf
heroku_user : iaxkzlaedvggqf
heroku_password : 320810e22b095f173b05acedb571fdc571dbdd57161c2d203af5651f0d8d4510
heroku_host : ec2-99-80-170-190.eu-west-1.compute.amazonaws.com
heroku_port : 5432

asset_classes : [crypto, fx, commodities, assets, bonds]


finnhub_key : cbcepm2ad3ib4g5ukl2g
cryptocompare_key : 70d54fd6e56db84eba0a9d9166b4d5da087c79d3d6cc0511e69144270f90c09b
coinmarketcap_key : 4317d033-2a95-4188-bba1-9441862d508e
quandl_key : H2wsJr5sJBEowokpwG4T
polygon_key : 5vybUVAguwTz5GCzOE9QqppqQPy_CwEJ
alphavantage_key : 1WEDCC91HCX5F7U4
financialmodeling_key : e6b9480f1fe2fa7d2b589cf7cd6f297



